[package]
name = "audio-core"
version = "0.1.0"
edition = "2024"

[dependencies]
lofty = "0.15.0"
regex = "1.10.0"
chrono = { version = "0.4.39", features = ["clock"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
